spring:
  profiles:
    active:
      - dev
---
spring:
  port: 8201
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test